# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true
contact_links:
- name: ğŸ™‹  Usage Questions
  url: https://github.com/arx-ast/discussions
  about: |
    Use Arx-AST's GitHub Discussions to ask "How do I do X with Cookiecutter?".
- name: ğŸ“–  Tutorial
  url: https://github.com/arx-ast
  about: |
    The Arx-AST tutorial is continually updated and provides an in depth walkthrough
    of how to use the latest release of Cookiecutter.
- name: ğŸ“  Arx-AST Code of Conduct
  url: https://github.com/arx-ast/coc/CODE_OF_CONDUCT.md
  about: Expectations for how people will interact with each other on Cookiecutter's GitHub.
